### ISSUE TITLE
Bug: tests that depend on files in tests/data fail (in CI, not locally)

### ISSUE THREAD

**Issue by rmm-ch** [sdsc-ordes/saving-willy#48]
Following the git-lfs fixes in dev (around 439ec7eb67327565dfa93eebe4f922dfcb2d81ac), the pytest has several tests that now fail, see e.g. this test run: https://github.com/sdsc-ordes/saving-willy/actions/runs/14704704136/job/41262067972

The failing tests all load files and validate that the metadata is read and handled correctly.

Locally these tests still pass, both using a standard session and an [act](https://nektosact.com/usage/index.html) runner. I have `git-lfs` installed on my machine, and although I didn't verify where `act` picks up the version from yet, it seems to have access inside its own container. 

adding the step:
```yaml
    - name: Check git-LFS is installed
      run: |
        which git-lfs
        /usr/bin/git-lfs --version 
```
locally produces:
```bash
| /usr/bin/git-lfs
| git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)
```

**Comment by rmm-ch** [comment]
Some routes to validate:

1. The action spec might require a step that installs git-lfs:

```yaml
      - name: Install Git LFS
        run: sudo apt-get update && sudo apt-get install -y git-lfs
      - name: Add Git LFS to PATH
        run: echo "/usr/bin/git-lfs" >> $GITHUB_PATH
```

2. or maybe just adding the directive on checkout: 
```yaml
    with:
      lfs: true
```
(The docs on https://github.com/actions/checkout are quite sparse on LFS)
